apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: wordpress
  labels:
     app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    
