apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath  
  resources:
    requests:
      storage: 1Gi